### ISSUE TITLE
[milestone] Compile a broad selection of compute shaders

### ISSUE THREAD

**Issue by damyanp** [llvm/wg-hlsl#11]
This is a milestone on the way to getting full HLSL support in Clang.

For this milestone we need to have enough features working in Clang that we can compile a broad selection of compute shaders, they pass the validator, and we can convince ourselves that the built shaders work correctly.

We can use the DML suite of shaders as a starting point, but we may identify other shaders that are worth testing.

The work items listed here are expected to be _fully_ completed - even if that means doing more than the bare minimum required to pass this milestone.

### Validation (#170)

- [x] llvm/llvm-project#116 
- [ ] llvm/llvm-project#117 
  - [x] llvm/llvm-project#120 
- [ ] llvm/llvm-project#118 
  - [ ] llvm/llvm-project#119 
  - [ ] llvm/llvm-project#121 

### Language (#21)
* [ ] Identify remaining language features for DirectML
* [x] https://github.com/llvm/llvm-project/issues/91640
* [x] https://github.com/llvm/llvm-project/issues/87526 (`out` and `inout` keywords)
* [x] https://github.com/llvm/llvm-project/issues/56067
* [x] llvm/llvm-project#125743
* [x] llvm/llvm-project#125754

### Tooling (#22)
- [ ] llvm/llvm-project#126257

### Resource Binding (#23)
* [x] llvm/llvm-project#110722
* [x] llvm/llvm-project#110723

### Root Signatures (#24)
  * [x] llvm/llvm-project#119032
    * [x] llvm/llvm-project#118896
      * [x] llvm/llvm-project#120472
      * [x] llvm/llvm-project#119014
      * [x] llvm/llvm-project#119011
      * [x] llvm/llvm-project#119019
      * [x] llvm/llvm-project#124595
    * [x] llvm/llvm-project#118897
      * [x] llvm/llvm-project#121493
      * [x] llvm/llvm-project#121487
      * [ ] llvm/llvm-project#121491
      * [x] llvm/llvm-project#121492
  * [ ] llvm/llvm-project#99523

### Semantics (#25)
* [x] llvm/llvm-project#114
* [ ] Support all compute semantics and lowering to DXIL ops
* [ ] llvm/llvm-project#129
* [ ] llvm/llvm-project#130
* [ ] llvm/llvm-project#131
* [ ] llvm/llvm-project#132
* [ ] llvm/llvm-project#133
* [ ] llvm/llvm-project#134
* [ ] llvm/llvm-project#135
* [ ] llvm/llvm-project#136
* [ ] llvm/llvm-project#137
* [ ] llvm/llvm-project#138
* [ ] llvm/llvm-project#139

### Intrinsics (#28)
- [x] llvm/llvm-project#30

### DXIL Shader Flags (#57)

- [x] llvm/llvm-project#113505

### Resources (#8)
- [ ] llvm/wg-hlsl#109
- [ ] llvm/wg-hlsl#10
- [x] llvm/wg-hlsl#333
- [x] llvm/wg-hlsl#125
- [x] llvm/wg-hlsl#126
- [x] llvm/wg-hlsl#127
- [x] llvm/wg-hlsl#128

> note: I've put a lot in the compute shaders milestone for now - it may make sense to shuffle some of this around.

### DirectX Container (#9)
- [ ] Add Root Signature part
- [ ] Generated container can be signed through DXV
- [ ] llvm/llvm-project#96674

**Comment by damyanp** [comment]
This is now tracked by issues with the "Epic" set to "DML Demo".
