### ISSUE TITLE
[milestone] Compile particle_life.hlsl

### ISSUE THREAD

**Issue by damyanp** [llvm/wg-hlsl#20]
This milestone shows that clang is able to compile and run a simple, but non-trivial, compute shader.

https://github.com/damyanp/dplife/blob/main/src/particle_life/particle_life.hlsl

### Language (#21)
* [x] Basic type declarations (e.g. `uint`, `int`, `half`, ...)
* [x] Vector type declarations (e.g. `vector<T,N>`, `float3`, `int4`, ...)
* [x] Vector cast-construction syntax (e.g. `float3(x,x,x)`)
* [x] Internal function linkage rules
* [x] cbuffer declarations
* [x] https://github.com/llvm/llvm-project/issues/106253

### Resource Binding (#23)
* [x] llvm/wg-hlsl#55
* [x] llvm/wg-hlsl#36

### Semantics (#25)

- [x] llvm/llvm-project#70122
- [x] llvm/llvm-project#70120

### DXIL Legalization and Lowering (#27)
* [ ] Inlining 
    * [x] https://github.com/llvm/llvm-project/issues/89282
* [ ]  Scalarization
    * [x] https://github.com/llvm/wg-hlsl/pull/62 
    * [x] https://github.com/llvm/wg-hlsl/pull/72
    * [x] https://github.com/llvm/llvm-project/issues/105178 
    * [x] https://github.com/llvm/llvm-project/issues/107433
    * [x] https://github.com/llvm/llvm-project/issues/107920

### Intrinsics (#28)
- [x] #29

### DXIL Shader Flags (#57)

- [x] llvm/llvm-project#112273
- [x] llvm/llvm-project#114557 
       Set based on properties of `DXIL::Opcode::BufferLoad`, if present, in the candidate function - see [here](https://github.com/microsoft/DirectXShaderCompiler/blob/a023a95f73618e8ca1791147d3722a3e1ea7608f/lib/DXIL/DxilShaderFlags.cpp#L605)
- [x] llvm/llvm-project#120119

### Resources (#8)
- [x] llvm/wg-hlsl#88
- [ ] llvm/wg-hlsl#41
- [x] llvm/wg-hlsl#68
- [x] llvm/wg-hlsl#56
- [x] llvm/wg-hlsl#74
- [x] llvm/wg-hlsl#122

### DirectX Container (#9)
- [x] #51
- [x] llvm/llvm-project#63835

**Comment by bogner** [comment]
As of llvm/llvm-project@ae6b4b23ea4291e937192a3c08d0f3c9835864c2 this is done.
