### ISSUE TITLE
[workstream] Resource Binding

### ISSUE THREAD

**Issue by damyanp** [llvm/wg-hlsl#23]
### Compile a runnable shader from clang (#7)
* [x] llvm/wg-hlsl#34
* [x] llvm/llvm-project#110719

### Compile particle_life.hlsl (#20)
* [x] llvm/wg-hlsl#55
* [x] llvm/wg-hlsl#36

### Compile a broad selection of compute shaders (#11)
* [x] llvm/wg-hlsl#176
* [x] llvm/wg-hlsl#177
* [x] llvm/llvm-project#110722
* [x] llvm/llvm-project#133346
* [x] llvm/llvm-project#110723

This issue probably depends on debug info and will need to be moved to a later milestone:
* [x] llvm/llvm-project#105059

### Ray Tracing (#18)
* [ ] Resource binding for libraries (`createHandleForLib`)

### V1 Release (#19)
* [ ] Dynamic resources binding

**Comment by damyanp** [comment]
These are all complete or tracked elsewhere, no need to keep this issue open.
