### ISSUE TITLE
[workstream] Intrinsics

### ISSUE THREAD

**Issue by damyanp** [llvm/wg-hlsl#28]
### Compile particle_life.hlsl (#20)
  * [x] Implement [`lerp](https://github.com/llvm/llvm-project/issues/70102) intrinsic
  * [x] Implement `abs` intrinsic
  * [ ] Implement [`normalize](https://github.com/llvm/llvm-project/issues/99139) intrinsic
  * [ ] Implement [`length](https://github.com/llvm/llvm-project/issues/99134) intrinsic
  * [ ] Implement [`saturate](https://github.com/llvm/llvm-project/issues/99154) intrinsic
### Compile all DML shaders, and they pass the validator (#11)
  * [x] implement `pow` intrinsic
  * [ ] implement [`f32tof16`](https://github.com/llvm/llvm-project/issues/99113) intrinsic
  * [ ] implement [`step`](https://github.com/llvm/llvm-project/issues/99157) intrinsic
  * [x] implement [`max`](https://github.com/llvm/llvm-project/issues/87072) intrinsic
  * [x] implement [`rcp`](https://github.com/llvm/llvm-project/issues/70100) intrinsic
  * [ ] implement [`asfloat`](https://github.com/llvm/llvm-project/issues/70098) intrinsic
  * [ ] implement [`ddx`](https://github.com/llvm/llvm-project/issues/99096) intrinsic
  * [x] implement `abs` intrinsic
  * [x] implement DirectX [`clamp`](https://github.com/llvm/llvm-project/issues/70071) intrinsic
  * [ ] implement SPIRV [`clamp`](https://github.com/llvm/llvm-project/issues/88052) intrinsic
  * [ ] implement [`saturate`](https://github.com/llvm/llvm-project/issues/99154) intrinsic
  * [ ] implement [`asuint`](https://github.com/llvm/llvm-project/issues/70097) intrinsic
  * [ ] implement SPIRV [`dot`](https://github.com/llvm/llvm-project/issues/88056) intrinsic
  * [x] implement DirectX [`dot`](https://github.com/llvm/llvm-project/issues/70073) intrinsic
  * [ ] implement [`clip`](https://github.com/llvm/llvm-project/issues/99093) intrinsic
  * [ ] implement [`mul`](https://github.com/llvm/llvm-project/issues/99138) intrinsic
  * [ ] implement [`cross`](https://github.com/llvm/llvm-project/issues/99095) intrinsic
  * [ ] implement [`reflect`](https://github.com/llvm/llvm-project/issues/99152) intrinsic
  * [ ] implement [`ddy`](https://github.com/llvm/llvm-project/issues/99099) intrinsic
  * [x] implement [`sqrt`](https://github.com/llvm/llvm-project/issues/86187) intrinsic
  * [ ] implement [`normalize`](https://github.com/llvm/llvm-project/issues/99139) intrinsic
  * [ ] implement [`f16tof32`](https://github.com/llvm/llvm-project/issues/99112) intrinsic
  * [x] implement [`lerp`](https://github.com/llvm/llvm-project/issues/70102) intrinsic
### V1 Release (#19)
- [ ] llvm/llvm-project#99235
