### ISSUE TITLE
Intrinsics used by particle_life.hlsl are implemented

### ISSUE THREAD

**Issue by damyanp** [llvm/wg-hlsl#29]
* [x] llvm/llvm-project#70102
* [x] llvm/llvm-project#99139
* [x] llvm/llvm-project#99134
* [x] llvm/llvm-project#99154
* [x] llvm/llvm-project#86155
