### ISSUE TITLE
CBuffers

### ISSUE THREAD

**Issue by bogner** [llvm/wg-hlsl#41]
- [x] llvm/wg-hlsl#50
- [x] llvm/llvm-project#122553
- [x] llvm/llvm-project#123406
- [x] llvm/llvm-project#113514
  - [x] llvm/llvm-project#118531
- [x] llvm/llvm-project#124630
- [x] llvm/llvm-project#123801
- [x] llvm/llvm-project#57914
- [x] llvm/llvm-project#122792
- [x] llvm/llvm-project#112992
- [x] microsoft/hlsl-specs#357

**Comment by damyanp** [comment]
Need to ensure we have issues filed for all of these items.

**Comment by hekota** [comment]
Done! :)
