### ISSUE TITLE
[milestone] Compile a runnable shader from clang

### ISSUE THREAD

**Issue by damyanp** [llvm/wg-hlsl#7]
This is a milestone on the way to getting full HLSL support in Clang.  

For this milestone we need to be able to compile a simple compute shader such that the resulting DXBC container can pass validation and be signed by the DXC validator and can therefore be executed on a non-developer mode Windows desktop PC. The shader compiler binary should come from some kind of nightly build, rather than building locally.

[Sample shader](https://godbolt.org/z/eK4K71r1s)

```hlsl
RWBuffer<int> In : register(u0);
RWBuffer<int> Out : register(u1);

[numthreads(8,1,1)]
void main(uint GI : SV_GroupIndex) {
  Out[GI] = In[GI] * In[GI];
}
```

### Language (#21)
* [x] `numthreads` entry attribute
* [x] Entry function linkage rules

### Resource Binding (#23)
* [x] llvm/wg-hlsl#34
* [ ] llvm/wg-hlsl#55
* [x] llvm/llvm-project#110719

### Semantics (#25)
* [x] Support `SV_GroupIndex` and `SV_DispatchThreadID` used with basic scalar/vector input types for target shader.

### Resources (#8)
- [x] llvm/llvm-project#101555
- [ ] llvm/llvm-project#101557
- [x] llvm/llvm-project#104271

### DirectX Container (#9)
- [x] llvm/llvm-project#103275
