### ISSUE TITLE
Validation for resource element types

### ISSUE THREAD

**Issue by damyanp** [llvm/wg-hlsl#74]
Most HLSL resource types accept an element type, through a template parameter:

```c++
RWBuffer<float2> buffer;
Texture2D<float4> texture;
StructuredBuffer<MyStruct> anotherBuffer;
```

- [x] #69 
- [x] #64 
- [x] llvm/llvm-project#113223
- [x] llvm/llvm-project#113224
- [x] llvm/llvm-project#75676

**Comment by bob80905** [comment]
Fixed and closed with https://github.com/llvm/llvm-project/pull/119643
