### ISSUE TITLE
[HLSL][DirectX] Resource Lowering ☂️

### ISSUE THREAD

**Issue by bogner** [llvm/wg-hlsl#8]
HLSL has buffer, texture, and sampler types that need to be lowered to resource representations when lowered to DXIL and SPIR-V.

- [ ] llvm/llvm-project#101555
- [ ] llvm/llvm-project#101557
- [ ] Structured buffers
- [ ] CBuffer resource types and operations
- [ ] Raw Buffers
- [ ] llvm/llvm-project#101558
- [ ] Sampler Feedback
- [ ] Input/Output patches
- [ ] Ray tracing payloads

Related tasks that need to be updated or refined:
- [ ] llvm/llvm-project#75830 
- [ ] llvm/llvm-project#58051 
- [ ] llvm/llvm-project#75981 
- [ ] llvm/llvm-project#57848
- [ ] llvm/llvm-project#58654

**Comment by damyanp** [comment]
@bogner - particle life seems to coincidentally be using alignment for structured buffers that work well, but @python3kgae suggests that there are more interesting alignment rules we need to consider here.  (This note to remind us to capture this somewhere in our plans).
