### ISSUE TITLE
Structured buffers

### ISSUE THREAD

**Issue by bogner** [llvm/wg-hlsl#88]
- [x] llvm/llvm-project#106189
- [x] llvm/llvm-project#112775
- [x] llvm/llvm-project#112776
- [x] llvm/llvm-project#112777
- [x] llvm/llvm-project#112977
- [x] llvm/llvm-project#112968
- [x] llvm/llvm-project#106188
- [x] llvm/llvm-project#121714
- [x] llvm/llvm-project#122663
