### ISSUE TITLE
[workstream] DirectX Container

### ISSUE THREAD

**Issue by damyanp** [llvm/wg-hlsl#9]
# Milestones

## Compile a runnable shader from Clang (#7)
- [ ] Resource support in PSV0 part

## Compile particle_life.hlsl
- [ ] Add Root Signature part
- [ ] Entry properties for Compute shader in PSV0 part.

## Compile all DML shaders, and they pass the validator
- [ ] Generated container can be signed through DXV

## Render Simple Triangle
- [ ] Semantic support in PSV0 part.
- [ ] Fill Input/Output Signature parts.

## Pixel and Vertex Shaders
- [ ] Entry properties for vertex and pixel shader in PSV0 part.

## Mesh Shaders
- [ ] Entry properties for mesh shader in PSV0 part.

## Ray Tracing
- [ ] Add Runtime Data part
